---
title: Données Enercoop et sociétaires (geo.enercoop.org)
ident: ''
description: >-
  Couches internes en géopackages contenant des données sur les Enercoop
  et des données sensibles sur les sociétaires
type: folder
children:

  - title: Enercoop locales
    ident: el
    description: >-
      Découpage des Els
    metadata_url: ''
    raw_data_url: https://geo.enercoop.org/data/enercoop/
    type: void_layer

  - title: Projets production
    ident: projets_production
    description: >-
      Ensemble des projets de production en cours ou achévés
    metadata_url: ''
    raw_data_url: https://geo.enercoop.org/data/enercoop/
    type: void_layer

  - title: Statistiques sociétaires par département
    ident: stats_societaires_dep
    description: >-
      Statistiques concernant les sociétaires au sein d'Enercoop
    metadata_url: https://si.enercoop.org/eprod:donnees:societariat
    raw_data_url: https://geo.enercoop.org/data/enercoop/
    type: void_layer

  - title: Sociétaires
    ident: ''
    description: >-
      Couches internes en géopackages contenant des données sensibles sur les sociétaires
    type: folder
    children:

    - title: Sociétaires LANG
      ident: societaires_lang
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Languedoc Roussilon
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/LANG/data/coopener/
      type: void_layer

    - title: Sociétaires RHOA
      ident: societaires_rhoa
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Auvergne-Rhône-Alpes
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/RHOA/data/coopener/
      type: void_layer

    - title: Sociétaires BRZH
      ident: societaires_brzh
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Bretagne
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/BRZH/data/coopener/
      type: void_layer

    - title: Sociétaires NPCP
      ident: societaires_npcp
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Hauts-de-France
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/NPCP/data/coopener/
      type: void_layer

    - title: Sociétaires MIPY
      ident: societaires_mipy
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Midi-Pyrénées
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/MIPY/data/coopener/
      type: void_layer

    - title: Sociétaires AQUI
      ident: societaires_aqui
      description: >- 
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Nouvelle-Aquitaine
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/AQUI/data/coopener/
      type: void_layer

    - title: Sociétaires NATL
      ident: societaires_natl
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Nationale
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/NATL/data/coopener/
      type: void_layer

    - title: Sociétaires ARDC
      ident: societaires_ardc
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Nord-est
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/ARDC/data/coopener/
      type: void_layer

    - title: Sociétaires ENOR
      ident: societaires_enor
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Normandie
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/ENOR/data/coopener/
      type: void_layer

    - title: Sociétaires PACA
      ident: societaires_paca
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Provence-Alpes-Côte-d'Azur
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/PACA/data/coopener/
      type: void_layer

    - title: Sociétaires PDLL
      ident: societaires_pdll
      description: >-
        Couches internes en géopackages contenant des données sensibles sur
        les sociétaires pour Enercoop Pays de la Loire
      metadata_url: https://si.enercoop.org/eprod:donnees:societariat
      raw_data_url: https://geo.enercoop.org/PDLL/data/coopener/
      type: void_layer
